using System.Text.Json.Serialization;
using Ai.Tlbx.MidTerm.Api.Models;
using Ai.Tlbx.MidTerm.Models;
using Ai.Tlbx.MidTerm.Models.Update;
using Ai.Tlbx.MidTerm.Settings;
using Ai.Tlbx.MidTerm.Common.Logging;
using Microsoft.AspNetCore.Mvc;

namespace Ai.Tlbx.MidTerm.Api;

[JsonSerializable(typeof(BootstrapResponse))]
[JsonSerializable(typeof(BootstrapLoginResponse))]
[JsonSerializable(typeof(FeatureFlags))]
[JsonSerializable(typeof(WsCommand))]
[JsonSerializable(typeof(WsCommandPayload))]
[JsonSerializable(typeof(WsCommandResponse))]
[JsonSerializable(typeof(WsSessionCreatedData))]
[JsonSerializable(typeof(SystemResponse))]
[JsonSerializable(typeof(TtyHostInfo))]
[JsonSerializable(typeof(HistoryPatchRequest))]
[JsonSerializable(typeof(LogSeverity))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(SessionListDto))]
[JsonSerializable(typeof(SessionInfoDto))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(RenameSessionRequest))]
[JsonSerializable(typeof(ResizeRequest))]
[JsonSerializable(typeof(ResizeResponse))]
[JsonSerializable(typeof(FileUploadResponse))]
[JsonSerializable(typeof(List<NetworkInterfaceDto>))]
[JsonSerializable(typeof(ShellInfoDto))]
[JsonSerializable(typeof(List<ShellInfoDto>))]
[JsonSerializable(typeof(MidTermSettingsPublic))]
[JsonSerializable(typeof(UpdateInfo))]
[JsonSerializable(typeof(LocalUpdateInfo))]
[JsonSerializable(typeof(UpdateType))]
[JsonSerializable(typeof(UpdateResult))]
[JsonSerializable(typeof(VersionManifest))]
[JsonSerializable(typeof(StateUpdate))]
[JsonSerializable(typeof(SystemHealth))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(List<UserInfo>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(AuthResponse))]
[JsonSerializable(typeof(AuthStatusResponse))]
[JsonSerializable(typeof(CertificateInfoResponse))]
[JsonSerializable(typeof(CertificateDownloadInfo))]
[JsonSerializable(typeof(SecurityStatus))]
[JsonSerializable(typeof(SharePacketInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo[]))]
[JsonSerializable(typeof(CursorStyleSetting))]
[JsonSerializable(typeof(ThemeSetting))]
[JsonSerializable(typeof(BellStyleSetting))]
[JsonSerializable(typeof(ClipboardShortcutsSetting))]
[JsonSerializable(typeof(TabTitleModeSetting))]
[JsonSerializable(typeof(LogSubscribeMessage))]
[JsonSerializable(typeof(LogEntryMessage))]
[JsonSerializable(typeof(LogHistoryMessage))]
[JsonSerializable(typeof(LogSessionsMessage))]
[JsonSerializable(typeof(LogSessionInfo))]
[JsonSerializable(typeof(List<LogSessionInfo>))]
[JsonSerializable(typeof(List<LogEntryMessage>))]
[JsonSerializable(typeof(LogFilesResponse))]
[JsonSerializable(typeof(LogFileInfo))]
[JsonSerializable(typeof(List<LogFileInfo>))]
[JsonSerializable(typeof(LogReadResponse))]
[JsonSerializable(typeof(SettingsWsMessage))]
[JsonSerializable(typeof(LaunchEntry))]
[JsonSerializable(typeof(List<LaunchEntry>))]
[JsonSerializable(typeof(CreateHistoryRequest))]
[JsonSerializable(typeof(FileCheckRequest))]
[JsonSerializable(typeof(FileCheckResponse))]
[JsonSerializable(typeof(FileRegisterRequest))]
[JsonSerializable(typeof(FileResolveResponse))]
[JsonSerializable(typeof(FilePathInfo))]
[JsonSerializable(typeof(DirectoryListResponse))]
[JsonSerializable(typeof(DirectoryEntry))]
[JsonSerializable(typeof(Dictionary<string, FilePathInfo>))]
[JsonSerializable(typeof(PathsResponse))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
public partial class AppJsonContext : JsonSerializerContext
{
}
