/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ChangePasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthStatusResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/security/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SecurityStatus'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/security/firewall': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FirewallRuleStatusResponse'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FirewallRuleStatusResponse'];
          };
        };
      };
    };
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FirewallRuleStatusResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SessionListDto'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': null | components['schemas']['CreateSessionRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SessionInfoDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{id}/resize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ResizeRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ResizeResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{id}/name': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: {
          auto?: boolean;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['RenameSessionRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{id}/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            file: components['schemas']['IFormFile'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileUploadResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{id}/bookmark': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SetBookmarkRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LaunchEntry'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateHistoryRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LaunchEntry'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/history/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['HistoryPatchRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LaunchEntry'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/history/{id}/star': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LaunchEntry'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/history/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['HistoryReorderRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['FileRegisterRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: {
          sessionId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['FileCheckRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileCheckResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          path: string;
          sessionId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DirectoryListResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/view': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          path: string;
          sessionId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          path: string;
          sessionId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/resolve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          sessionId: string;
          path: string;
          deep?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileResolveResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/files/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: {
          sessionId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['FileSaveRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileSaveResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logs/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LogFilesResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logs/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          file: string;
          lines?: number;
          fromEnd?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LogReadResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logs/tail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          file: string;
          position?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LogReadResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateShareLinkRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateShareLinkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/claim': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ClaimShareRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ClaimShareResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/share/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ShareBootstrapResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BootstrapResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bootstrap/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BootstrapLoginResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemHealth'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/version/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['VersionManifest'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/certificate/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CertificateInfoResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/certificate/download/pem': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/certificate/download/mobileconfig': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/certificate/share-packet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SharePacketInfo'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/networks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NetworkInterfaceDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/shells': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ShellInfoDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserInfo'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MidTermSettingsPublic'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['MidTermSettingsPublic'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings/reload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/paths': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PathsResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateInfo'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: {
          source?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update/result': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          clear?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update/log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthResponse: {
      success: boolean;
      error: null | string;
    };
    AuthStatusResponse: {
      authenticationEnabled: boolean;
      passwordSet: boolean;
    };
    /** @enum {unknown} */
    BellStyleSetting: 'notification' | 'sound' | 'visual' | 'both' | 'off';
    BootstrapLoginResponse: {
      certificate: null | components['schemas']['CertificateInfoResponse'];
    };
    BootstrapResponse: {
      auth: components['schemas']['AuthStatusResponse'];
      version: string;
      ttyHostVersion: null | string;
      ttyHostCompatible: boolean;
      /** Format: int64 */
      uptimeSeconds: number;
      platform: string;
      hostname: string;
      settings: components['schemas']['MidTermSettingsPublic'];
      networks: components['schemas']['NetworkInterfaceDto'][];
      users: components['schemas']['UserInfo'][];
      shells: components['schemas']['ShellInfoDto'][];
      updateResult: null | components['schemas']['UpdateResult'];
      devMode: boolean;
      features: components['schemas']['FeatureFlags'];
      voicePassword: null | string;
      gitVersion: null | string;
      codeSigned: boolean;
    };
    CertificateDownloadInfo: {
      fingerprint: string;
      fingerprintFormatted: string;
      /** Format: date-time */
      notBefore: string;
      /** Format: date-time */
      notAfter: string;
      keyProtection: string;
      dnsNames: string[];
      ipAddresses: string[];
      isFallbackCertificate: boolean;
    };
    CertificateInfoResponse: {
      fingerprint: null | string;
      /** Format: date-time */
      notBefore: null | string;
      /** Format: date-time */
      notAfter: null | string;
      isFallbackCertificate: boolean;
    };
    ChangePasswordRequest: {
      currentPassword?: null | string;
      newPassword: string;
    };
    ClaimShareRequest: {
      grantId: string;
      secret: string;
    };
    ClaimShareResponse: {
      grantId: string;
      sessionId: string;
      mode: components['schemas']['ShareAccessMode'];
      /** Format: date-time */
      expiresAtUtc: string;
    };
    /** @enum {unknown} */
    ClipboardShortcutsSetting: 'auto' | 'windows' | 'unix';
    CreateHistoryRequest: {
      shellType: string;
      executable: string;
      commandLine?: null | string;
      workingDirectory: string;
      dedupeKey?: null | string;
      isStarred: boolean;
      label?: null | string;
    };
    CreateSessionRequest: {
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      shell?: null | string;
      workingDirectory?: null | string;
    };
    CreateShareLinkRequest: {
      sessionId: string;
      mode: components['schemas']['ShareAccessMode'];
      shareHost?: null | string;
    };
    CreateShareLinkResponse: {
      shareUrl: string;
      grantId: string;
      mode: components['schemas']['ShareAccessMode'];
      /** Format: date-time */
      expiresAtUtc: string;
    };
    /** @enum {unknown} */
    CursorInactiveStyleSetting: 'outline' | 'block' | 'bar' | 'underline' | 'none';
    /** @enum {unknown} */
    CursorStyleSetting: 'bar' | 'block' | 'underline';
    DirectoryEntry: {
      name: string;
      isDirectory: boolean;
      /** Format: int64 */
      size: null | number;
      /** Format: date-time */
      modified: null | string;
      mimeType: null | string;
    };
    DirectoryListResponse: {
      path: string;
      entries: components['schemas']['DirectoryEntry'][];
    };
    FeatureFlags: {
      voiceChat: boolean;
    };
    FileCheckRequest: {
      paths: string[];
    };
    FileCheckResponse: {
      results: {
        [key: string]: components['schemas']['FilePathInfo'];
      };
    };
    FilePathInfo: {
      exists: boolean;
      /** Format: int64 */
      size: null | number;
      isDirectory: boolean;
      mimeType: null | string;
      /** Format: date-time */
      modified: null | string;
      isText: null | boolean;
    };
    FileRegisterRequest: {
      sessionId: string;
      paths: string[];
    };
    FileResolveResponse: {
      exists: boolean;
      resolvedPath: null | string;
      isDirectory: boolean;
      /** Format: int64 */
      size: null | number;
      mimeType: null | string;
      /** Format: date-time */
      modified: null | string;
      isText: null | boolean;
    };
    FileSaveRequest: {
      path: string;
      content: string;
    };
    FileSaveResponse: {
      success: boolean;
      /** Format: int64 */
      size: number;
    };
    FileUploadResponse: {
      path: string;
    };
    FirewallRuleStatusResponse: {
      supported: boolean;
      canManage: boolean;
      rulePresent: boolean;
      ruleEnabled: boolean;
      matchesCurrentPort: boolean;
      matchesCurrentProgram: boolean;
      /** Format: int32 */
      port: number;
      bindAddress: string;
      loopbackOnly: boolean;
      ruleName: string;
      ruleLocalPort: null | string;
      ruleProgramPath: null | string;
    };
    HistoryPatchRequest: {
      isStarred?: null | boolean;
      label?: null | string;
    };
    HistoryReorderRequest: {
      orderedIds: string[];
    };
    /** Format: binary */
    IFormFile: string;
    /** @enum {unknown} */
    LanguageSetting: 'auto' | 'en' | 'zh' | 'es' | 'hi' | 'fr' | 'bn' | 'pt' | 'ru' | 'ja' | 'de';
    LaunchEntry: {
      id: string;
      shellType: string;
      executable: string;
      commandLine: null | string;
      workingDirectory: string;
      isStarred: boolean;
      label: null | string;
      /** Format: date-time */
      lastUsed: string;
      /** Format: int32 */
      order: number;
    };
    LocalUpdateInfo: {
      available: boolean;
      version: string;
      path: string;
      type: components['schemas']['UpdateType'];
      sessionsPreserved: boolean;
    };
    LogEntryMessage: {
      messageType: string;
      source: string;
      sessionId: null | string;
      timestamp: string;
      level: string;
      message: string;
    };
    LogFileInfo: {
      name: string;
      source: string;
      sessionId: null | string;
      /** Format: int64 */
      size: number;
      modified: string;
      isActive: boolean;
    };
    LogFilesResponse: {
      files: components['schemas']['LogFileInfo'][];
    };
    LogReadResponse: {
      entries: components['schemas']['LogEntryMessage'][];
      /** Format: int64 */
      position: number;
      fileName: string;
    };
    LoginRequest: {
      password: string;
    };
    ManagerBarButton: {
      id: string;
      label: string;
      text: string;
    };
    MidTermSettingsPublic: {
      defaultShell: null | components['schemas']['ShellType'];
      /** Format: int32 */
      defaultCols: number;
      /** Format: int32 */
      defaultRows: number;
      defaultWorkingDirectory: string;
      /** Format: int32 */
      fontSize: number;
      fontFamily: string;
      cursorStyle: components['schemas']['CursorStyleSetting'];
      cursorBlink: boolean;
      cursorInactiveStyle: components['schemas']['CursorInactiveStyleSetting'];
      hideCursorOnInputBursts: boolean;
      theme: components['schemas']['ThemeSetting'];
      terminalColorScheme: components['schemas']['TerminalColorSchemeSetting'];
      backgroundImageEnabled: boolean;
      backgroundImageFileName: null | string;
      /** Format: int64 */
      backgroundImageRevision: number;
      backgroundImageFit: string;
      /** Format: int32 */
      uiTransparency: number;
      tabTitleMode: components['schemas']['TabTitleModeSetting'];
      /** Format: double */
      minimumContrastRatio: number;
      smoothScrolling: boolean;
      scrollbarStyle: components['schemas']['ScrollbarStyleSetting'];
      useWebGL: boolean;
      /** Format: int32 */
      scrollbackLines: number;
      bellStyle: components['schemas']['BellStyleSetting'];
      copyOnSelect: boolean;
      rightClickPaste: boolean;
      clipboardShortcuts: components['schemas']['ClipboardShortcutsSetting'];
      terminalEnterMode: components['schemas']['TerminalEnterModeSetting'];
      scrollbackProtection: boolean;
      keepSystemAwakeWithActiveSessions: boolean;
      inputMode: string;
      fileRadar: boolean;
      tmuxCompatibility: boolean;
      managerBarEnabled: boolean;
      devMode: boolean;
      showChangelogAfterUpdate: boolean;
      showUpdateNotification: boolean;
      updateChannel: string;
      language: components['schemas']['LanguageSetting'];
      managerBarButtons: components['schemas']['ManagerBarButton'][];
      runAsUser: null | string;
      runAsUserSid: null | string;
      authenticationEnabled: boolean;
      certificatePath: null | string;
    };
    NetworkEndpointInfo: {
      name: string;
      url: string;
    };
    NetworkInterfaceDto: {
      name: string;
      ip: string;
    };
    PathsResponse: {
      settingsFile: string;
      secretsFile: string;
      certificateFile: string;
      logDirectory: string;
    };
    RenameSessionRequest: {
      name?: null | string;
    };
    ResizeRequest: {
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      viewerId?: null | string;
    };
    ResizeResponse: {
      accepted: boolean;
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
    };
    /** @enum {unknown} */
    ScrollbarStyleSetting: 'off' | 'hover' | 'always';
    SecurityStatus: {
      passwordProtected: boolean;
      certificateTrusted: boolean;
      warnings: string[];
    };
    SessionInfoDto: {
      id: string;
      /** Format: int32 */
      pid: number;
      /** Format: date-time */
      createdAt: string;
      isRunning: boolean;
      /** Format: int32 */
      exitCode: null | number;
      /** Format: int32 */
      cols: number;
      /** Format: int32 */
      rows: number;
      shellType: string;
      name: null | string;
      terminalTitle: null | string;
      manuallyNamed: boolean;
      currentDirectory: null | string;
      /** Format: int32 */
      foregroundPid: null | number;
      foregroundName: null | string;
      foregroundCommandLine: null | string;
      /** Format: int32 */
      order: number;
      parentSessionId: null | string;
      bookmarkId: null | string;
    };
    SessionListDto: {
      sessions: components['schemas']['SessionInfoDto'][];
    };
    SetBookmarkRequest: {
      bookmarkId: string;
    };
    /** @enum {unknown} */
    ShareAccessMode: 'ViewOnly' | 'FullControl';
    ShareBootstrapResponse: {
      hostname: string;
      session: null | components['schemas']['SessionInfoDto'];
      settings: components['schemas']['MidTermSettingsPublic'];
      mode: components['schemas']['ShareAccessMode'];
      /** Format: date-time */
      expiresAtUtc: string;
    };
    SharePacketInfo: {
      certificate: components['schemas']['CertificateDownloadInfo'];
      endpoints: components['schemas']['NetworkEndpointInfo'][];
      trustPageUrl: string;
      /** Format: int32 */
      port: number;
    };
    ShellInfoDto: {
      type: string;
      displayName: string;
      isAvailable: boolean;
      supportsOsc7: boolean;
    };
    /** @enum {unknown} */
    ShellType: 'Pwsh' | 'PowerShell' | 'Cmd' | 'Bash' | 'Zsh' | null;
    SystemHealth: {
      healthy: boolean;
      mode: string;
      /** Format: int32 */
      sessionCount: number;
      version: string;
      /** Format: int32 */
      webProcessId: number;
      /** Format: int64 */
      uptimeSeconds: number;
      platform: string;
      ttyHostVersion: null | string;
      ttyHostExpected: null | string;
      ttyHostCompatible: null | boolean;
      /** Format: int32 */
      windowsBuildNumber: null | number;
    };
    SystemResponse: {
      healthy: boolean;
      version: string;
      manifest: components['schemas']['VersionManifest'];
      /** Format: int32 */
      sessionCount: number;
      /** Format: int64 */
      uptimeSeconds: number;
      platform: string;
      ttyHost: components['schemas']['TtyHostInfo'];
      /** Format: int32 */
      webProcessId: number;
      /** Format: int32 */
      windowsBuildNumber: null | number;
    };
    /** @enum {unknown} */
    TabTitleModeSetting:
      | 'hostname'
      | 'static'
      | 'sessionName'
      | 'terminalTitle'
      | 'foregroundProcess';
    /** @enum {unknown} */
    TerminalColorSchemeSetting:
      | 'auto'
      | 'dark'
      | 'light'
      | 'solarizedDark'
      | 'solarizedLight'
      | 'matrix';
    /** @enum {unknown} */
    TerminalEnterModeSetting: 'default' | 'shiftEnterLineFeed';
    /** @enum {unknown} */
    ThemeSetting: 'dark' | 'light' | 'solarizedDark' | 'solarizedLight';
    TtyHostInfo: {
      version: null | string;
      expected: null | string;
      compatible: boolean;
    };
    UpdateInfo: {
      available: boolean;
      currentVersion: string;
      latestVersion: string;
      releaseUrl: string;
      downloadUrl: null | string;
      assetName: null | string;
      releaseNotes: null | string;
      type: components['schemas']['UpdateType'];
      sessionsPreserved: boolean;
      environment: null | string;
      localUpdate: null | components['schemas']['LocalUpdateInfo'];
      isDowngrade: boolean;
    };
    UpdateResult: {
      found: boolean;
      success: boolean;
      message: string;
      details: string;
      timestamp: string;
      logFile: string;
    };
    /** @enum {unknown} */
    UpdateType: 'none' | 'webOnly' | 'full';
    UserInfo: {
      username: string;
      sid: null | string;
      /** Format: int32 */
      uid: null | number;
      /** Format: int32 */
      gid: null | number;
    };
    VersionManifest: {
      web: string;
      pty: string;
      /** Format: int32 */
      protocol: number;
      minCompatiblePty: string;
      checksums: null | {
        [key: string]: string;
      };
      signature: null | string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
