using System.Text.Json.Serialization;
using Ai.Tlbx.MidTerm.Models;
using Ai.Tlbx.MidTerm.Models.Git;
using Ai.Tlbx.MidTerm.Models.Update;
using Ai.Tlbx.MidTerm.Settings;
using Microsoft.AspNetCore.Mvc;

namespace Ai.Tlbx.MidTerm.Services;

[JsonSerializable(typeof(BootstrapResponse))]
[JsonSerializable(typeof(BootstrapLoginResponse))]
[JsonSerializable(typeof(FeatureFlags))]
[JsonSerializable(typeof(WsCommand))]
[JsonSerializable(typeof(WsCommandPayload))]
[JsonSerializable(typeof(WsCommandResponse))]
[JsonSerializable(typeof(WsSessionCreatedData))]
[JsonSerializable(typeof(SystemResponse))]
[JsonSerializable(typeof(TtyHostInfo))]
[JsonSerializable(typeof(HistoryPatchRequest))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(SessionListDto))]
[JsonSerializable(typeof(SessionInfoDto))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(RenameSessionRequest))]
[JsonSerializable(typeof(ResizeRequest))]
[JsonSerializable(typeof(ResizeResponse))]
[JsonSerializable(typeof(FileUploadResponse))]
[JsonSerializable(typeof(List<NetworkInterfaceDto>))]
[JsonSerializable(typeof(ShellInfoDto))]
[JsonSerializable(typeof(List<ShellInfoDto>))]
[JsonSerializable(typeof(MidTermSettings))]
[JsonSerializable(typeof(MidTermSettingsPublic))]
[JsonSerializable(typeof(UpdateInfo))]
[JsonSerializable(typeof(LocalUpdateInfo))]
[JsonSerializable(typeof(UpdateType))]
[JsonSerializable(typeof(UpdateResult))]
[JsonSerializable(typeof(VersionManifest))]
[JsonSerializable(typeof(StateUpdate))]
[JsonSerializable(typeof(SystemHealth))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(List<UserInfo>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(AuthResponse))]
[JsonSerializable(typeof(AuthStatusResponse))]
[JsonSerializable(typeof(CertificateInfoResponse))]
[JsonSerializable(typeof(CertificateDownloadInfo))]
[JsonSerializable(typeof(SecurityStatus))]
[JsonSerializable(typeof(SharePacketInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo[]))]
[JsonSerializable(typeof(CursorStyleSetting))]
[JsonSerializable(typeof(ThemeSetting))]
[JsonSerializable(typeof(BellStyleSetting))]
[JsonSerializable(typeof(ClipboardShortcutsSetting))]
[JsonSerializable(typeof(ScrollbarStyleSetting))]
[JsonSerializable(typeof(SettingsWsMessage))]
[JsonSerializable(typeof(LaunchEntry))]
[JsonSerializable(typeof(List<LaunchEntry>))]
[JsonSerializable(typeof(CreateHistoryRequest))]
[JsonSerializable(typeof(FileCheckRequest))]
[JsonSerializable(typeof(FileCheckResponse))]
[JsonSerializable(typeof(FileRegisterRequest))]
[JsonSerializable(typeof(FileResolveResponse))]
[JsonSerializable(typeof(FilePathInfo))]
[JsonSerializable(typeof(DirectoryListResponse))]
[JsonSerializable(typeof(DirectoryEntry))]
[JsonSerializable(typeof(Dictionary<string, FilePathInfo>))]
[JsonSerializable(typeof(PathsResponse))]
[JsonSerializable(typeof(ManagerBarButton))]
[JsonSerializable(typeof(List<ManagerBarButton>))]
[JsonSerializable(typeof(MainBrowserStatusMessage))]
[JsonSerializable(typeof(FileTreeResponse))]
[JsonSerializable(typeof(FileTreeEntry))]
[JsonSerializable(typeof(FileTreeEntry[]))]
[JsonSerializable(typeof(CommandDefinition))]
[JsonSerializable(typeof(CommandListResponse))]
[JsonSerializable(typeof(CreateCommandRequest))]
[JsonSerializable(typeof(UpdateCommandRequest))]
[JsonSerializable(typeof(RunCommandRequest))]
[JsonSerializable(typeof(ReorderCommandsRequest))]
[JsonSerializable(typeof(CommandRunStatus))]
[JsonSerializable(typeof(GitStageRequest))]
[JsonSerializable(typeof(GitUnstageRequest))]
[JsonSerializable(typeof(GitCommitRequest))]
[JsonSerializable(typeof(GitPushPullRequest))]
[JsonSerializable(typeof(GitStashRequest))]
[JsonSerializable(typeof(GitDiscardRequest))]
[JsonSerializable(typeof(GitDiffRequest))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
public partial class AppJsonContext : JsonSerializerContext
{
}
