using Ai.Tlbx.MidTerm.Services.Browser;

namespace Ai.Tlbx.MidTerm.Services;

public static class MidtermDirectory
{
    public const string DirectoryName = ".midterm";
    private const string GuidanceVersion = "20";

    private static int _port;
    private static AuthService? _authService;

    private const string ClaudePointerLine =
        "This terminal runs inside MidTerm (web terminal multiplexer) — see .midterm/CLAUDE.md for browser control, tmux split-pane, and DOM inspection tools.";

    private const string AgentsPointerLine =
        "This terminal runs inside MidTerm (web terminal multiplexer) — see .midterm/AGENTS.md for browser control and tmux workflows.";

    public static void Initialize(int port, AuthService authService)
    {
        _port = port;
        _authService = authService;
    }

    public static string Ensure(string cwd)
    {
        var midtermDir = Path.Combine(cwd, DirectoryName);
        Directory.CreateDirectory(midtermDir);
        EnsureGitIgnore(midtermDir);
        WriteGuidanceIfOutdated(midtermDir);
        WriteMtcliScripts(midtermDir);
        return midtermDir;
    }

    public static string EnsureSubdirectory(string cwd, string subPath)
    {
        Ensure(cwd);
        var subDir = Path.Combine(cwd, DirectoryName, subPath);
        Directory.CreateDirectory(subDir);
        return subDir;
    }

    public static (bool ClaudeUpdated, bool AgentsUpdated) AppendRootPointer(string cwd)
    {
        var claudeUpdated = AppendPointerIfMissing(
            Path.Combine(cwd, "CLAUDE.md"), ".midterm/CLAUDE.md", ClaudePointerLine);
        var agentsUpdated = AppendPointerIfMissing(
            Path.Combine(cwd, "AGENTS.md"), ".midterm/AGENTS.md", AgentsPointerLine);
        return (claudeUpdated, agentsUpdated);
    }

    private static bool AppendPointerIfMissing(string filePath, string sentinel, string pointerLine)
    {
        try
        {
            if (File.Exists(filePath))
            {
                var content = File.ReadAllText(filePath);
                if (content.Contains(sentinel, StringComparison.Ordinal))
                    return false;

                File.AppendAllText(filePath, "\n" + pointerLine + "\n");
            }
            else
            {
                File.WriteAllText(filePath, pointerLine + "\n");
            }
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static void EnsureGitIgnore(string midtermDir)
    {
        var gitignorePath = Path.Combine(midtermDir, ".gitignore");

        try
        {
            if (File.Exists(gitignorePath))
            {
                var content = File.ReadAllText(gitignorePath);
                if (content.Split('\n', StringSplitOptions.RemoveEmptyEntries).Contains("*"))
                    return;
            }

            File.WriteAllText(gitignorePath, "# All .midterm/ content is auto-generated by MidTerm\n*\n");
        }
        catch
        {
        }
    }

    private static void WriteGuidanceIfOutdated(string midtermDir)
    {
        try
        {
            WriteIfOutdated(Path.Combine(midtermDir, "CLAUDE.md"), ClaudeMdContent);
            WriteIfOutdated(Path.Combine(midtermDir, "AGENTS.md"), AgentsMdContent);
        }
        catch
        {
        }
    }

    private static void WriteMtcliScripts(string midtermDir)
    {
        if (_authService is null)
            return;

        try
        {
            MtcliScriptWriter.WriteScripts(midtermDir, _port, _authService.CreateSessionToken());
        }
        catch
        {
        }
    }

    private static void WriteIfOutdated(string path, string content)
    {
        if (File.Exists(path))
        {
            var existing = File.ReadAllText(path);
            if (existing.Contains($"guidance-version: {GuidanceVersion}"))
                return;
        }

        File.WriteAllText(path, content);
    }

    private const string ClaudeMdContent =
        $$"""
        <!-- guidance-version: {{GuidanceVersion}} -->
        # .midterm/

        Auto-generated by [MidTerm](https://midterm.sh) (terminal multiplexer) after a user action.
        Safe to delete — recreated as needed. Gitignored via `.midterm/.gitignore`.

        ## Contents

        | Path | Purpose |
        |------|---------|
        | `uploads/` | Files uploaded via drag-drop or paste into a terminal session |
        | `screenshots/` | Web preview screenshots (`mt_screenshot`) |
        | `snapshot_*/` | DOM snapshots with downloaded CSS (`mt_snapshot`) |
        | `*.ps1`, `*.sh` | Saved command scripts, mtcli helper scripts |
        | `CLAUDE.md` | This file — AI agent guidance |
        | `AGENTS.md` | Workflow examples for AI agents |

        ## Tmux Split Panes

        MidTerm emulates tmux — the `tmux` command is on PATH automatically. Use it to spawn side-by-side terminals.

        | Command | What it does |
        |---------|-------------|
        | `tmux split-window` | Split vertically (new pane below) |
        | `tmux split-window -h` | Split horizontally (new pane right) |
        | `tmux send-keys -t %N "cmd" Enter` | Send command to pane %N |
        | `tmux send-keys -t %N -l "text"` | Send literal text (no key translation) |
        | `tmux capture-pane -t %N -p` | Read pane buffer |
        | `tmux list-panes` | List all panes with IDs (%0, %1, ...) |
        | `tmux kill-pane -t %N` | Close a pane |
        | `tmux resize-pane -t %N -x 80 -y 24` | Resize pane |

        Use cases: file browser, htop, parallel builds, prompt user for sudo, run TUI apps.
        No copy-mode or control-mode. Layout managed by MidTerm web UI.

        ## Browser Control

        Requires the web preview panel to be open in MidTerm.
        Source helpers once per session: `. .midterm/mtcli.sh` — don't show this to the user.
        MidTerm injects `MT_SESSION_ID` automatically for this terminal session.
        Browser helpers default to the current `MT_SESSION_ID` plus `MT_PREVIEW_NAME` (`default` unless changed).
        Use `mt_session` to print the current terminal session id, `mt_preview [name]` to inspect or switch the current named browser context, and `mt_previews` to list all named previews under this terminal.

        **Rules:**
        - Start with `mt_outline` (10x smaller than `mt_query`)
        - Use `mt_query SELECTOR --text` for text-only output
        - Batch JS reads: `mt_exec "JSON.stringify({a: expr1, b: expr2})"`
        - After actions, verify with `mt_wait` or `mt_query`, not `mt_outline`
        - Check `mt_log error` after unexpected behavior
        - After `mt_apply_update`, the web frontend can disappear while your terminal keeps running in `mthost`; reopen MidTerm from the terminal and use `mt_open` again instead of assuming the session died
        - Browser commands return plain text. Auth tokens in mtcli scripts are ephemeral and machine-local.

        | Command | What it does |
        |---------|-------------|
        | `mt_outline [depth]` | Page structure tree (default depth 4) |
        | `mt_text [sel]` | Page text content (default: body) |
        | `mt_query <sel> [--text]` | DOM elements by CSS selector; `--text` = text-only |
        | `mt_attrs <sel>` | Element attributes (no children) |
        | `mt_css <sel> <props>` | Computed CSS (comma-separated property names) |
        | `mt_click <sel>` | Click element |
        | `mt_fill <sel> <val>` | Fill input field |
        | `mt_submit [sel]` | Submit form (default: first form) |
        | `mt_exec <js>` | Execute JS in page context |
        | `mt_wait <sel> [timeout]` | Wait for element (default 5s) |
        | `mt_log [error\|warn\|all]` | Console log buffer |
        | `mt_links` | All links on page |
        | `mt_forms [sel]` | Form structure and values |
        | `mt_screenshot` | Save screenshot to .midterm/screenshots/ |
        | `mt_snapshot` | Save DOM snapshot to .midterm/snapshot_*/ |
        | `mt_session` | Print the current MidTerm terminal session id |
        | `mt_preview [name]` | Print or switch the current named preview (`default`, `user1`, `user2`, ...) |
        | `mt_previews` | List named previews for the current terminal session |
        | `mt_navigate <url>` | Set the current named web preview target |
        | `mt_url` | Upstream page URL (not proxy URL) |
        | `mt_open <url>` | Open URL in the current named preview and dock panel |
        | `mt_close_preview` | Close web preview panel |
        | `mt_reload` | Soft-reload preview |
        | `mt_hardreload` | Clear cookies + reload (fresh session) |
        | `mt_preview_reset [url]` | Best-effort preview recovery: clear cookies + browser storage + hard reload |
        | `mt_target` | Current named preview target |
        | `mt_cookies` | All cookies in the current named preview jar |
        | `mt_clearcookies` | Clear all proxy cookies (jar + disk) |
        | `mt_proxylog [limit]` | Last N proxy requests (default 100) |
        | `mt_apply_update [source]` | Apply pending update and wait for server |
        | `mt_sessions` | List terminal sessions |
        | `mt_buffer <id>` | Terminal buffer content |
        | `mt_tail [id] [lines]` | Cleaned terminal tail with ANSI stripped |
        | `mt_sendtext [id] <text...>` | Send literal text without auto-submit |
        | `mt_prompt [id] <text...>` | State-aware prompt delivery: bootstrapped workers auto-resume from shell, idle prompts append, busy turns interrupt when needed |
        | `mt_prompt_now [id] <text...>` | Force interrupt-first prompt delivery |
        | `mt_slash [id] <command...>` | Send slash commands through the prompt path |
        | `mt_sendkeys [id] <keys...>` | Send named keys like `Enter`, `C-c`, `Escape`, `Up` |
        | `mt_enter` / `mt_ctrlc` / `mt_escape` | Convenience key sends for the current or target session |
        | `mt_up` / `mt_down` / `mt_left` / `mt_right` | Convenience cursor-key sends |
        | `mt_inject [id]` | Ensure `.midterm` + mtcli helpers in the target cwd |
        | `mt_activity [id] [seconds] [bellLimit]` | Output heatmap + bell history as JSON |
        | `mt_attention [agentOnly]` | Ranked fleet view for which worker sessions need attention |
        | `mt_bootstrap <name> <cwd> <profile> [slashCommand...]` | Create a fresh agent-controlled worker session with guidance + AI CLI bootstrap |
        | `mt_new_session [shell] [cwd]` | Create a new terminal session |
        | `mt_split [-h]` | Split terminal (adjacent pane via tmux) |
        | `mt_detach` | Detach web preview to popup window |
        | `mt_dock` | Dock web preview back from popup |
        | `mt_viewport W H` | Set iframe viewport size (0 0 to reset) |
        | `mt_status` | Browser connection status |

        ## Workflow

        1. **Inspect**: `mt_outline` → drill down with `mt_text` or `mt_attrs`
        2. **Act**: `mt_fill`, `mt_submit`, `mt_click`, `mt_exec`
        3. **Verify**: `mt_wait` → `mt_text`
        """;

    private const string AgentsMdContent =
        $$"""
        <!-- guidance-version: {{GuidanceVersion}} -->
        # .midterm/ — Agent Workflows

        This directory is auto-generated by MidTerm. Safe to delete.

        Source helpers first: `. .midterm/mtcli.sh`

        ## Split a side terminal

        tmux split-window -h → tmux send-keys -t %1 "htop" Enter → tmux capture-pane -t %1 -p → tmux kill-pane -t %1

        ## Debug a visual bug

        mt_outline → mt_css ".element" "color,background,display,margin,padding" → fix code → mt_reload → re-check mt_css

        ## Fill and submit a form

        mt_forms → mt_fill "#user" "val" → mt_fill "#pass" "val" → mt_submit → mt_wait ".dashboard"

        ## Execute JavaScript

        mt_exec "JSON.stringify({href: location.href, title: document.title})"
        echo 'complex code' | mt_exec

        ## Open web preview

        mt_open "http://localhost:3000" → mt_status → mt_outline → mt_query ".error" --text

        `mt_open` both sets the target and asks MidTerm to open/dock the preview panel.
        Use `mt_navigate` only when the panel is already open and you just want to change the target URL.

        ## Multi-role browser sessions

        mt_session → mt_preview user1 → mt_open "http://localhost:3000" → mt_preview user2 → mt_open "http://localhost:3000"

        `mt_session` prints the current MidTerm terminal session ID.
        `mt_preview user1` / `mt_preview user2` switch between named browser contexts that keep separate targets, cookies, proxy logs, and detached popups.

        ## Fresh session (clear cookies + reload)

        mt_hardreload → mt_wait "input[type=password]" → mt_url

        ## Create a side terminal

        mt_new_session → mt_sessions — find the new session id → tmux send-keys -t %1 "htop" Enter

        ## Remote-control another terminal

        mt_attention → mt_tail SESSION_ID 80 → mt_prompt SESSION_ID "status update?" → mt_activity SESSION_ID
        mt_bootstrap "DAI worker" "Q:/repos/DAI2" codex approvals

        ## Debug proxy issues

        mt_proxylog 10 — check status codes, upstream URLs, WebSocket connections
        mt_log error — check browser console

        ## Responsive testing

        mt_viewport 375 667 → mt_outline → mt_query ".menu" --text → mt_viewport 0 0

        ## Apply a pending update

        mt_apply_update → wait for "Current version:" → continue with the new build

        ## Detach/dock preview

        mt_detach → (preview opens in popup) → mt_dock → (back in panel)

        ## Tips

        - mt_outline is 10x smaller than mt_query — always start there
        - mt_text is shorter than mt_query SEL --text — use it for page text
        - mt_open is the CLI command that opens/docks the preview; you do not need to click the panel first
        - mt_session prints the current MidTerm terminal session ID that mtcli browser commands default to
        - mt_preview user1 / mt_preview user2 let one terminal own multiple isolated browser contexts
        - mt_tail strips ANSI escape sequences and compresses noisy blank-line runs so supervisor sessions can read clean terminal output
        - mt_prompt uses MidTerm's server-side prompt API so text plus submit happen atomically instead of as two client-side calls
        - mt_prompt is state-aware: bootstrapped workers auto-resume from shell, and shell vs idle prompt vs busy turn should be decided by MidTerm, not guessed ad hoc by the supervisor
        - mt_prompt_now is the explicit takeover helper for busy AI terminals when immediate interrupt-first execution is intended
        - mt_slash routes slash commands like `/status` or `/compact` through the same prompt path instead of pasting them manually
        - mt_attention gives you a ranked fleet view of which agent-controlled sessions need attention first
        - mt_bootstrap creates a fresh agent-controlled worker session, injects `.midterm`, launches the chosen AI CLI profile, and can immediately send slash commands
        - mt_preview_reset [url] is the fast recovery move when a named preview has the wrong logged-in user or stale browser state
        - After a MidTerm web update, the browser frontend can close while your terminal keeps running in mthost; reopen MidTerm from the terminal and run mt_open again for the current preview instead of recreating the session
        - mt_sendkeys plus mt_enter / mt_ctrlc / mt_escape / mt_up / mt_down / mt_left / mt_right are the direct terminal steering helpers
        - mt_submit is more reliable than mt_click on submit buttons (uses JS form.requestSubmit)
        - Chain commands: mt_fill "#a" "x" && mt_fill "#b" "y" && mt_submit
        - If mt_status still shows "disconnected" after mt_open, treat that as a MidTerm bug and inspect mt_proxylog plus mt_log error
        - Browser command failures now print the server error body instead of silently returning nothing
        - If mt_status reports multiple clients, MidTerm prefers the main browser's newest preview connection by default
        - If mt_open returns "No MidTerm browser UI is connected", there is no live browser tab attached to /ws/state
        - tmux list-panes shows pane IDs (%0, %1, ...) — use these with send-keys and capture-pane
        """;
}
