using Ai.Tlbx.MidTerm.Services.Browser;

namespace Ai.Tlbx.MidTerm.Services;

public static class MidtermDirectory
{
    public const string DirectoryName = ".midterm";
    private const string GuidanceVersion = "8";

    private static int _port;
    private static AuthService? _authService;

    private const string ClaudePointerLine =
        "This terminal runs inside MidTerm (web terminal multiplexer) — see .midterm/CLAUDE.md for browser control, tmux split-pane, and DOM inspection tools.";

    private const string AgentsPointerLine =
        "This terminal runs inside MidTerm (web terminal multiplexer) — see .midterm/AGENTS.md for browser control and tmux workflows.";

    public static void Initialize(int port, AuthService authService)
    {
        _port = port;
        _authService = authService;
    }

    public static string Ensure(string cwd)
    {
        var midtermDir = Path.Combine(cwd, DirectoryName);
        Directory.CreateDirectory(midtermDir);
        EnsureGitIgnore(midtermDir);
        WriteGuidanceIfOutdated(midtermDir);
        WriteMtcliScripts(midtermDir);
        return midtermDir;
    }

    public static string EnsureSubdirectory(string cwd, string subPath)
    {
        Ensure(cwd);
        var subDir = Path.Combine(cwd, DirectoryName, subPath);
        Directory.CreateDirectory(subDir);
        return subDir;
    }

    public static (bool ClaudeUpdated, bool AgentsUpdated) AppendRootPointer(string cwd)
    {
        var claudeUpdated = AppendPointerIfMissing(
            Path.Combine(cwd, "CLAUDE.md"), ".midterm/CLAUDE.md", ClaudePointerLine);
        var agentsUpdated = AppendPointerIfMissing(
            Path.Combine(cwd, "AGENTS.md"), ".midterm/AGENTS.md", AgentsPointerLine);
        return (claudeUpdated, agentsUpdated);
    }

    private static bool AppendPointerIfMissing(string filePath, string sentinel, string pointerLine)
    {
        try
        {
            if (File.Exists(filePath))
            {
                var content = File.ReadAllText(filePath);
                if (content.Contains(sentinel, StringComparison.Ordinal))
                    return false;

                File.AppendAllText(filePath, "\n" + pointerLine + "\n");
            }
            else
            {
                File.WriteAllText(filePath, pointerLine + "\n");
            }
            return true;
        }
        catch
        {
            return false;
        }
    }

    private static void EnsureGitIgnore(string midtermDir)
    {
        var gitignorePath = Path.Combine(midtermDir, ".gitignore");

        try
        {
            if (File.Exists(gitignorePath))
            {
                var content = File.ReadAllText(gitignorePath);
                if (content.Split('\n', StringSplitOptions.RemoveEmptyEntries).Contains("*"))
                    return;
            }

            File.WriteAllText(gitignorePath, "# All .midterm/ content is auto-generated by MidTerm\n*\n");
        }
        catch
        {
        }
    }

    private static void WriteGuidanceIfOutdated(string midtermDir)
    {
        try
        {
            WriteIfOutdated(Path.Combine(midtermDir, "CLAUDE.md"), ClaudeMdContent);
            WriteIfOutdated(Path.Combine(midtermDir, "AGENTS.md"), AgentsMdContent);
        }
        catch
        {
        }
    }

    private static void WriteMtcliScripts(string midtermDir)
    {
        if (_authService is null)
            return;

        try
        {
            MtcliScriptWriter.WriteScripts(midtermDir, _port, _authService.CreateSessionToken());
        }
        catch
        {
        }
    }

    private static void WriteIfOutdated(string path, string content)
    {
        if (File.Exists(path))
        {
            var existing = File.ReadAllText(path);
            if (existing.Contains($"guidance-version: {GuidanceVersion}"))
                return;
        }

        File.WriteAllText(path, content);
    }

    private const string ClaudeMdContent =
        $$"""
        <!-- guidance-version: {{GuidanceVersion}} -->
        # .midterm/

        Auto-generated by [MidTerm](https://midterm.sh) (terminal multiplexer) after a user action.
        Safe to delete — recreated as needed. Gitignored via `.midterm/.gitignore`.

        ## Contents

        | Path | Purpose |
        |------|---------|
        | `uploads/` | Files uploaded via drag-drop or paste into a terminal session |
        | `screenshots/` | Web preview screenshots (`mt_screenshot`) |
        | `snapshot_*/` | DOM snapshots with downloaded CSS (`mt_snapshot`) |
        | `*.ps1`, `*.sh` | Saved command scripts, mtcli helper scripts |
        | `CLAUDE.md` | This file — AI agent guidance |
        | `AGENTS.md` | Workflow examples for AI agents |

        ## Tmux Split Panes

        MidTerm emulates tmux — the `tmux` command is on PATH automatically. Use it to spawn side-by-side terminals.

        | Command | What it does |
        |---------|-------------|
        | `tmux split-window` | Split vertically (new pane below) |
        | `tmux split-window -h` | Split horizontally (new pane right) |
        | `tmux send-keys -t %N "cmd" Enter` | Send command to pane %N |
        | `tmux send-keys -t %N -l "text"` | Send literal text (no key translation) |
        | `tmux capture-pane -t %N -p` | Read pane buffer |
        | `tmux list-panes` | List all panes with IDs (%0, %1, ...) |
        | `tmux kill-pane -t %N` | Close a pane |
        | `tmux resize-pane -t %N -x 80 -y 24` | Resize pane |

        Use cases: file browser, htop, parallel builds, prompt user for sudo, run TUI apps.
        No copy-mode or control-mode. Layout managed by MidTerm web UI.

        ## Browser Control

        Requires the web preview panel to be open in MidTerm.
        Source helpers once per session: `. .midterm/mtcli.sh` — don't show this to the user.

        **Rules:**
        - Start with `mt_outline` (10x smaller than `mt_query`)
        - Use `mt_query SELECTOR true` for text-only output
        - Batch JS reads: `mt_exec "JSON.stringify({a: expr1, b: expr2})"`
        - After actions, verify with `mt_wait` or `mt_query`, not `mt_outline`
        - Check `mt_log error` after unexpected behavior
        - All commands return JSON. Auth tokens in mtcli scripts are ephemeral and machine-local.

        | Command | What it does |
        |---------|-------------|
        | `mt_outline [depth]` | Page structure tree (default depth 4) |
        | `mt_query <sel> [true]` | DOM elements by CSS selector; `true` = text-only |
        | `mt_attrs <sel>` | Element attributes (no children) |
        | `mt_css <sel> <props>` | Computed CSS (comma-separated property names) |
        | `mt_click <sel>` | Click element |
        | `mt_fill <sel> <val>` | Fill input field |
        | `mt_exec <js>` | Execute JS in page context |
        | `mt_wait <sel> [timeout]` | Wait for element (default 5s) |
        | `mt_log [error\|warn\|all]` | Console log buffer |
        | `mt_links` | All links on page |
        | `mt_forms [sel]` | Form structure and values |
        | `mt_screenshot` | Save screenshot to .midterm/screenshots/ |
        | `mt_snapshot` | Save DOM snapshot to .midterm/snapshot_*/ |
        | `mt_navigate <url>` | Set web preview target |
        | `mt_open <url>` | Open URL in web preview (alias for mt_navigate) |
        | `mt_close_preview` | Close web preview panel |
        | `mt_reload` | Soft-reload preview |
        | `mt_target` | Current preview target |
        | `mt_cookies` | Server-side cookie jar |
        | `mt_proxylog [limit]` | Last N proxy requests (default 100) |
        | `mt_sessions` | List terminal sessions |
        | `mt_buffer <id>` | Terminal buffer content |
        | `mt_new_session [shell] [cwd]` | Create a new terminal session |
        | `mt_split [-h]` | Split terminal (adjacent pane via tmux) |
        | `mt_detach` | Detach web preview to popup window |
        | `mt_dock` | Dock web preview back from popup |
        | `mt_viewport W H` | Set iframe viewport size (0 0 to reset) |
        | `mt_status` | Browser connection status |

        ## Workflow

        1. **Inspect**: `mt_outline` → drill down with `mt_attrs` or `mt_css`
        2. **Act**: `mt_click`, `mt_fill`, `mt_exec`
        3. **Verify**: `mt_wait` or `mt_query SEL true`
        """;

    private const string AgentsMdContent =
        $$"""
        <!-- guidance-version: {{GuidanceVersion}} -->
        # .midterm/ — Agent Workflows

        This directory is auto-generated by MidTerm. Safe to delete.

        Source helpers first: `. .midterm/mtcli.sh`

        ## Split a side terminal

        tmux split-window -h → tmux send-keys -t %1 "htop" Enter → tmux capture-pane -t %1 -p → tmux kill-pane -t %1

        ## Debug a visual bug

        mt_outline → mt_css ".element" "color,background,display,margin,padding" → fix code → mt_reload → re-check mt_css

        ## Fill and submit a form

        mt_forms → mt_fill "#user" "val" → mt_fill "#pass" "val" → mt_click "button[type=submit]" → mt_wait ".dashboard"

        ## Execute JavaScript

        mt_exec "JSON.stringify({href: location.href, title: document.title})"
        echo 'complex code' | mt_exec

        ## Open web preview

        mt_open "http://localhost:3000" → mt_outline → mt_query ".error" true

        ## Create a side terminal

        mt_new_session → mt_sessions — find the new session id → tmux send-keys -t %1 "htop" Enter

        ## Debug proxy issues

        mt_proxylog 10 — check status codes, upstream URLs, WebSocket connections
        mt_log error — check browser console

        ## Responsive testing

        mt_viewport 375 667 → mt_outline → mt_query ".menu" true → mt_viewport 0 0

        ## Detach/dock preview

        mt_detach → (preview opens in popup) → mt_dock → (back in panel)

        ## Tips

        - mt_outline is 10x smaller than mt_query — always start there
        - mt_query SEL true returns text-only (no HTML tags)
        - Chain commands: mt_fill "#a" "x" && mt_fill "#b" "y" && mt_click "#submit"
        - If mt_status shows "disconnected", the web preview panel needs to be open in MidTerm
        - tmux list-panes shows pane IDs (%0, %1, ...) — use these with send-keys and capture-pane
        """;
}
